CppWriter uses sbt managed scala (not system scala)

diff --git a/compiler/lib/test/codegen/CppWriter/run b/compiler/lib/test/codegen/CppWriter/run
--- a/compiler/lib/test/codegen/CppWriter/run
+++ b/compiler/lib/test/codegen/CppWriter/run
@@ -4,9 +4,6 @@
 
 cpp_doc_ok()
 {
-  ./hpp > C.hpp && \
-  ./cpp > C.cpp && \
-  ./otherCpp > Other.cpp && \
   gcc -c C.cpp Other.cpp
 }
 
@@ -14,21 +11,14 @@ tests="
 cpp_doc_ok
 "
 
-echo 'compiling Scala source'
-if ! ./build > build_log.txt 2>&1
+echo 'generating C++ with the project Scala version'
+if ! (cd ../../../.. && ./fpp-sbt --batch \
+  'lib/Test/runMain generateCppDoc lib/test/codegen/CppWriter') \
+  > build_log.txt 2>&1
 then
-  echo 'compilation failed'
-  echo 'scalac version 2.13.1 or greater required'
+  echo 'Scala compilation or C++ generation failed'
   echo 'see build_log.txt' for details
-  exit 0
-fi
-
-if ! ./hpp > hpp_log.txt 2>&1
-then
-  echo 'cannot run hpp'
-  echo 'scala version 3.4 or earlier is required'
-  echo 'see hpp_log.txt' for details
-  exit 0
+  exit 1
 fi
 
 run_suite $tests
